swagger: "2.0"
info:
  title: "Bug Swagger"
  version: "1.0"
basePath: /
paths:
  /greeting/{name}:
    post:
      summary: Generate greeting
      description: Generates a greeting message.
      operationId: bug.main.greeting_bug
      produces:
        - text/plain;
      responses:
        200:
          description: greeting response
          schema:
            type: string
          examples:
            "text/plain": "Hello John"
      parameters:
        - name: name
          in: path
          description: Name of the person to greet.
          required: true
          type: string
        - name: queryA
          in: query
          required: true
          type: string
        - name: queryB
          in: query
          required: false
          type: string
